"""empty message

Revision ID: 65524f234e99
Revises: 60cd00ec6838
Create Date: 2024-04-14 15:04:25.226346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65524f234e99'
down_revision = '60cd00ec6838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    op.drop_table('_alembic_tmp_workout_exercises')
    op.drop_table('user_workouts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_weight', sa.Integer(), nullable=True))

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goal_weight')

    op.create_table('user_workouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_workouts_user_id_users'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='fk_user_workouts_workout_id_workouts'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_workout_exercises',
    sa.Column('workout_id', sa.INTEGER(), nullable=True),
    sa.Column('exercise_id', sa.INTEGER(), nullable=True),
    sa.Column('sets', sa.INTEGER(), nullable=False),
    sa.Column('reps', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_workout_exercises_exercise_id_exercises'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='fk_workout_exercises_workout_id_workouts'),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id')
    )
    op.create_table('goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('start_weight', sa.INTEGER(), nullable=True),
    sa.Column('goal_weight', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_goals_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
