"""empty message

Revision ID: 8c6bd74e2c9c
Revises: d6c91ca14a67
Create Date: 2024-04-16 17:05:18.193019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6bd74e2c9c'
down_revision = 'd6c91ca14a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(), nullable=False))

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
