"""empty message

Revision ID: d6c91ca14a67
Revises: ba804b703bcb
Create Date: 2024-04-16 17:02:38.775286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c91ca14a67'
down_revision = 'ba804b703bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(), nullable=False))

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
