"""Added a new column to the User model

Revision ID: e060a4525220
Revises: 961ef1d73d31
Create Date: 2024-04-11 12:28:35.686608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e060a4525220'
down_revision = '961ef1d73d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_pull', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('push_pull')

    # ### end Alembic commands ###
